local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb(data) m=string.sub(data, 0, 55) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


local b=WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('AjVlTYiXltaSjYKAcFqCSGKGbMPYCpWtEloQbXzvYMkabvUlPNIypFDQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrLw==')
function jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(data) m=string.sub(data, 0, 55) data=data:gsub(m,WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('wenhAxIpbRpfyhDeFIDxglKjpKZiHtCVZwGrXGACATRhLdkwcyvRARb'))

data = string.gsub(data, WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('TVoZOvEUfBDUxKrowlcGJzGXZkHOcAEWEUjNzBLECVvfhHrjFPgTuuqW14=')..b..WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('iWCRaQFCuRcWlvSBmREeTzwWOZZYsOAibixUczHpAESQHQmBeLQLiJKPV0='), WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('fdKbPDmmSFDjlIZvipIQDYRxDEhEhcGyedbstgGwEDoiIugxnmatXGF')) return (data:gsub(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('EbUvTRfwZQexVdpOTEhYkaJRloVXMhAykwgbOHgUBYkNVbKdItbaoKlLg=='), function(x) if (x == WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('vSLSAXTmDwLovfmxtunOwmmbGHVzwOJlRclBhBzPOAgaxcMvrXWObwZPQ==')) then return WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('HFsTrNnZXrRwYilnxqtDQmyGlHNYdWbAAHVGvskwpNzrBBCgQZiEaNA') end local r,f=WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('hXTeFQfjWfAtiGuncFtmutGmHIkDQkVvSclhcgGuSQJBPIjxiUNDnCr'),(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('AanUOEwzfjEtPQhEosxJWOOHwQorwhDohNloQYIzkfsxaUTNSWjDcVYMQ==') or WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('XqCwEWmwKNEtWgGQgQqVVNPRUgoTRrqJyPEhHDjjNUekGkXykVLhRgEMA==')) end return r; end):gsub(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('OlrXpGSpNjSCAtbUtWgzoKeuyvbxzdfKVmbhkWtKNXcHZBYgXbVaRFYJWQlZCVkPyVkPyVkPyVkPyVkPyVkPw=='), function(x) if (#x ~= 8) then return WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('mEQdwTSWiDmdYdOWnLNYIrqSCzqaIoKElsjpHRkkwJEgLbtmLomUCDt') end local c=0 for i=1,8 do c=c+(x:sub(i,i)==WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('iLSksuWIGWUtJjzlEivZwOVpLaeNUNdhYVXWqUNagjwpNCzbvcqPfbOMQ==') and 2^(8-i) or 0) end return string.char(c) end)) end


 


local Furious = loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('DpLAAoOcFSXWrQeplCROUlLHUfTybaUhFJcBRDVXaAwLaMcQwZwzAyHWERCUmlraHh2Q2pSb0hHZndXWVpyVEluUUFxRGd4dGd4bE1YWFZnU0dJTnBQdUx2cWludXpQS2FIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDNaemNYcDZMMDFsY21OMWNua3RWV2t0VEdsaUwyMWhhVzR2VTI5MWNtTmxMbXgxWVE9PQ=='))))()

local GUI = Furious:Create{
    Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('QVYTBBRSiCJsEXyDSnLDfOOgxiUYeKuDCnEveTvxxToDcgYHkRRIDlQcWZqSkt4ZXVWRXpVUUpvckRlcW5MeWtPTnpJYXdTbFJLUGR4Z3ZkbXdWakRabEl4TUJHRktPclJuVnlhVzkxY3c9PQ==')),
    Size = UDim2.fromOffset(600, 400),
    Theme = Furious.Themes.Dark,
    Link = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('qvBVBvjiKmZQMwWdYImlumnHVuvxvksJnHeXpXRTgLGQamrZRARLUtLYmFJR2NtR3VqSVh4UldudVRkc1BRVUNCdUhjTXpWT3NBQlFra2pWY01ySXRRVHJjaVhRVUNVdWFIUjBjSE02THk5a2FYTmpiM0prTG1kbkwyVjFkV2hRWVdKRFMwbz0='))
}

local Tab = GUI:Tab{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('zHPDEBSEyYwREQeKaZMmyAIRlOdRLEmCoNslXTtAwqmaFaCXyDrFMIBZ1ZIVVhZTldoYURna2dmRm9jVURJQ2Z1a1JwQ0lnZnJFYktoYWhFbEtXQ3pmaFhDbGJZbkFCclRXRnBiZz09')),
	Icon = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('hiCOXKTRzKmnhqyjOOxTeyhyxgylssUqwaBswlEOYofwCCOjtZzDcYeSUlFQnBFWWlzdmV1SlJ1b1BYQUJQbmZOSUp1bFFDWnFiaW9pbkJMS3RHV2t2c1d5VXhHYmlzbGNtSjRZWE56WlhScFpEb3ZMekkzT1RBeE56STRPREk9'))
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('sJdrktnFaDrxoCkZcHrkZrtaCGJBVBfJnfNbtovOiEAoLaOvFlAImYFVEZYcmpnTG9zQmZXVFRpT0NrSnJ2d2VydWFMdU9IamNZblNkWnNKTUZHZlBVbVhxVmtabU1oRFFteGhaR1VnUW1Gc2JBPT0=')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('iNCwEoZVtsjTEbuswYNKeNAtwSLQJoQpsDQOwSqomWgBouNEODPdbzibkR0cmt4b01DWmxCYk50WFVIaE9JVHRUSHdIWGhhZ1BkQWltZFZscm1FV1dwWGdNQ3pwVEdGSWFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDFOdmVVRmtjbWxaVkM5UWFYUmlkV3hzU0hWaUxTMHZiV0ZwYmk5RVpYTjBjbTk1WlhJPQ==')), true))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('eWisVmtoZGPjudBNKuTzcrNLFiVbnvkqGUZNavDjAmVFEnesLExExJkd3BQYWdubmFtamFqV3VIZE1Bb3RuY0hoeGJSRlFiREphQ05pbE5aVE9RT0FkaW9FY3BVUUhBblFteGhaR1VnUW1Gc2JDQldNZz09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('qmabQxcWiDQZpxWTQnkNXNetWymPwDbQDoZeWXrapXjcLujmMEdoVLZcWtaenZLeUVyTktWdk5JWHRhQmZZZmJWQnRUSkhGbFZMZnFFTXpLU3V3cGVORUtvbEZMUm5oRmFIUjBjSE02THk5amIyUmxOSHBoWVM1NGVYb3ZjMk55YVhCMEwzTmpjbWx3ZEMxc2IyRmtaWEl1YkhWaA=='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('quULJxbXhchAAaYakrkgymjntRlVppoHJszlqvvApdMGeoSYLWxKKgKbEhyemJ6Y0llYUxhWm5KTm52SnpDSEFUaVBKcE1pd1dJV3dxWWlteVl4bVRlbk9uUnJ6ZGtXeFIzSmhibVFnVUdsbFkyVWdUMjVzYVc1bElId2dTMFZa')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('BlWKksLHKdZjXqBnWGptYcvgHHqFNWNBDvvxXlMrnPQPHWojxAHmKACWWpsbEx1dmtxZFJGWE5WdVN3d0N2TU9uWlVwaVBCYkV1RXlzWGV3VUR3VVdnV0lZTmhGdE5wZGFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDFScGJHbDBaWE4wWVdOamIzVnVkQzlKWkdzdmJXRnBiaTlUZEdGeVNIVmlVbVZpYjNKdQ=='))))()

	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('oSUnHhiHNFrAsHWDQUarCgJqosNwetBIybqtRFqECWlgyBfqLBBbschcFl3Y0NncENKREJDR2R4S0tLRE9DblZHdmlZUndOTlNYU2ZjUWd5eHFiam5MR0dXSm5ucmliaFVrVTZJRmhNSUNoU1JVeEZRVk5GS1E9PQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('eXhoVryPLjWfFYzbGWNjTRPYxoBBpLdjEmsvMuxYeWSTerTvpQCSYaIUnJIVFdxQnpKRnNNaFBFd1NnWWtxdURIT0NYTlNtSnFPTFhubHZZSlJ6S0tJVUtrcFBxaGtxcGFIUjBjSE02THk5d1lYTjBaV0pwYmk1amIyMHZjbUYzTDFGYVZFdEhNREZN')), true))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('fNbhSXBobMVOnyafJOBgZpDdAWolHLuOiszfDghtkNkgCisFyshiSAZemZQQlR1a291SmxUcFpIdG90YWxQWkRTWFR5VGh2S1hsWlBNbU9UcHRpUmNtaW5TSVpyWHZvZlRYVnlaR1Z5SUUxNWMzUmxjbmtnTWc9PQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('ZLOxcldXcSYtEEiebwvFkbKWEGBlHuKTURoqKAtlVKqefvVBQNBZRjMQkZCeHJ1Z1J3emZ6VGN3ZHRma3lBaVdZaEV2S0dZTE15R3FsZGFuS2hYTmNNU3NFWEZ2bWxjaGFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDFOcGJYQnNlVk5sYm5ScGJtVnNMM0l6ZEdndmJXRnBiaTlzYjJGa1pYSXViSFZo'))))()

	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('AZnkzlBxiDZaPjjRfdWErOjSDOQMZEHJcmWcOpGLsKugjdhqlmGJcKceENVWW9uSEdQVFB3T1poWUtxU3dPVmJob1hxTERheFNsS3llY0lZaEVVTWRpVWtwRG5Xalp6ZFNtRnBiR0p5WldGcg==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('aqPcfQPKlpjwlHYQGaCkkhNPWqsZTpRpMbRcBANxExovMinZJlRGGaiek9XQUFRemNwSmtlS21IVmt2S1hjd2dyWFFHem5CV2VsT3loT2RSUG9CVFdlSVNNTHhmQU5ISWFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBKc2FYUjZTWE5MYVc1bkwxVnVhWFpsY25OaGJFWmhjbTB2YldGcGJpOU1iMkZrWlhJdlVtVm5kV3hoY2c9PQ=='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('HyhMafTHTZsXUjMIJDdLAmPuAibrkICDQBtXOqyqpQFLEzHiLfYXVCidHBrWGdwSlVRWnBmU2JHQmlnWHNHZ2psc1h3QnVLT0NMZ09SZWh5VnZMTWJ4dFJHenpWTkhmblVHaGhiblJ2YlNCR2IzSmpaWE09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('XpbtRjoOuYKgnaSwOjoEvQIjaHFkRIaUmhvfiRXEXERiGlaKRytUaxCRFRxWE9lbmdEY01Yb0NTakxOa1JhYURmQWV5TGxaTHhua2hwVVNmZENpaElOclJGT0dVTVVjUmFIUjBjSE02THk5d1lYTjBaV0pwYmk1amIyMHZjbUYzTHpSM1ZVSnFVM2hT'))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('VBfeVwZifhftgpSmpLOJDPtogsviuTyLiEYLXOrkPieuNHKlQiVFNfVUVdPU2p5Rk5aTnB1RWNKUEZLTnNpbU9VTFNIZmpIU3BoaVlNWnhESXJzcEJ1SkdtSG9tWlJEdVFYSnpaVzVoYkE9PQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('MevePGlEBCQspDsMfBAQutvVQqEMzwYnkaRHzuclwxWuedlIHhyppNxbFlUWnl4Y0dKeFBrYWRUVHJuT01uV0xNS3BUZFp3UnJGVUd2SmhpR2dOdXN5V0ZucmttUGhlcmFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBSSldscFpkMmwwYUdFekwwRnljMlZ1VEdsaUwyMWhhVzR2UVhKemIyNU5ZV2x1TG14MVlRPT0='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('fFJqqMwNzHkAZCmeblpgiBpMiRxpzdbBITAeEuNKhjmrZJLHqZkIrSlWEdaS3lOQlZ6andqcU5CU2RBSXhHRHJNa29sd1Nuc3ZkdkxCWmlUYnVFVVZqekh2V0RwZUptQlJHRm9iMjlrSUUxdlpHUmxaQT09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGetAsync(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('DzEpmQuqxcJmaaSivvkputgexGELDaeSMKUzHygfKWjXyBdSLPUtMHpU2l4eVB3b29UbU1rTllVU0luQ0FCUHNOZEpGVEF1SnliQ0FxaktVR1hTQUFKQ0F2VUNIQWF6bmFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDFKcGNIQmxaV1F2UkdGSWIyOWthVzVoY25rdmJXRnBiaTlqYUdGeWFXOTBjM2RoY21VPQ=='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('KwqeSrFAGKIiFKjBUXAWMCWtBrzYTchhCarYaVtVdNvzpJprUxsDtmvYmVOVGp2TFJobnRxcmVES0pDUlBXTlVpc1Z1Ym5PaXBOTm14ZFVNcm9IdE9lYnRCUVF1bWZwclJHRm9iMjlr')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGetAsync(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('upCzPtFEswiLFoCjTZjanzMbzdfAQQJKwzzFfSJAtRQgExltNuTogIWWE5HaVpHcEtnSW1meGlEY0prVFVQTnFUb2xiRnN6dGJ6ampuZm1LZG1VaGdDa3FCUUladXFiTGFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDFKcGNIQmxaV1F2UkdGSWIyOWthVzVoY25rdmJXRnBiaTlqYUdGeWFXOTBjM2RoY21VPQ=='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('jpBcyRRcElLMgSrjTHFJRinldFehPbBLrnmhyYhmIEcIIXzIkkdCTdSV1JZYW1VdkZoTVlZQ0Z6RXhqdFNLdGR1dllRZk9kS3JmUk5FUG5Rc0hTUENndXdrblhiUWVtd1FteGhaR1VnUW1Gc2JDQkVkVzVuWlc5dQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('KkIunsAsbFXSbDRsiRooizxQUzhrpDXaUvGxvAGVTsnyMQMUOXktrahZEd3U3JudmFURHhtb0ZRWVlIUE1KbnV5dEpjdkFuQlRreGhqV05pekxkYWxxaW10cXpkZGZxZWFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBaR1NqRXZVbTlpYkc5NExVVjRjR3h2YVhSekwyMWhhVzR2YzJOeWFYQjBjeTlDYkdGa1pVSmhiR3hGZG1WdWRDNXNkV0U9'))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('pONVhhseMnMbgxvtnliOYqUdDzeTOubMxJVrnMgYGvAEApuEPYDOZRibVJOa0ROWFNmWXd1Z0pUdVdnUmtBQnlsclRDeFdxUUpqd1BJeU5MZHZXcHJmd3Vva0xXZ3hkdFFXNXBiV1VnUW1Gc2JBPT0=')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('OnppqlXPENNweDKrYLWQAUEtrrkWAsSEhEylHFQBLTUARizEqNmuYSrb0l0UkhEQ1RtaG1DcnNWaFlBZ1lKdFhlT3BFQ1NoUHRnbkNsT1dwZFJvZ1hSWndqUHhnVHdSUmFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBaR1NqRXZVbTlpYkc5NExVVjRjR3h2YVhSekwyMWhhVzR2YzJOeWFYQjBjeTlNYjJGa1pYSXViSFZo'))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('mxLeckxSJoWDHtcgaiYCKIdwhuOgOhYsgZAaJfsknqOPVgxSXWozIeVSXVoVHpwbUNQRXFYZFlwemNVQUJyZU9XTUZxaFVnbkFEb09PTlJsRXd3alpueHlnQmNOb0duTFUzUnliMjVuWlhOMElHSmhkSFJzWldkeWIzVnVaSE09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('GPdWhgMMkzZbWQrnEXgDkZMLCYSEwHOtDPychYeFCeYGCTFPVbeeeTscFV2d0xlcm1HTVh4YndpRFFQS0tSWlhLTnRETklXa1JiVXNxSWN0T1RKVk5hVnlWV1RxTWpBR2FIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBaR1NqRXZVbTlpYkc5NExVVjRjR3h2YVhSekwyMWhhVzR2YzJOeWFYQjBjeTlVVTBKVmRHbHNjeTVzZFdFPQ=='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('VICUYUaNieUulRTyDXkNPRDjUsFxvWPkLZxZipdxzCYZEhnItqmaBkrbXJKRHFrbWxSd3p1RFBxdXd1WnJkUkR6Vm15YVlLbHhtZElob25oY25JREJBR0xFeEh2YVdlY1JHOXZjbk09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('SbZPnwGcUlDSnHhNdOpZtKdsXZZECTcAeAwbQcaPdWsejEfPUTRIBVuUERKQnNCQXVwcGlJbkRYU3JhTUlNeENBZ2JqZnRuQ3JLaHpmY2lub2FwcGZ0d0ltUVVPdURrUGFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBaR1NqRXZVbTlpYkc5NExVVjRjR3h2YVhSekwyMWhhVzR2YzJOeWFYQjBjeTlNYjJGa1pYSXViSFZo'))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('DcSZyZlXVxQnmkkCpQXMSpPePYAUSERNZATBsJQfkzmtiWlIoKAaGMLWmt4TEZSdEFHdW5EdUhWQXBNS0xLTVBha0JvcHlEeVFicG9JWWVyTGdWaWpFQW5sc1VaUUNIeU16QXdPQT09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('wwbCELrxPzgJHyHwaierWNXUggEdQYbKPQGAwNmNqneHsPVCbcXRDwlUU1ZVXpPVkNESVpCcmFmUVBsQ0tYYUVNZkdNYXNsaUlic3BNeUpkU3RUZWN2Vmdtc2ZLRXRYbGFIUjBjSE02THk5elkzSnBjSFJpYkc5NExtTnZiUzl5WVhjdk16QXdPQzB5TGpjeExVOVFMVWRGVkMxR1QwOUVMVFUxTXpnPQ=='))))() 
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('lwTOZzLXTMTUljLhWKDfQPkCJrQVYZfeucrYHbnDnvOZUJxbiLTnENHWE5wYVFwbUlZVFd3ZUNtTkpkTmVob2lKcnJGeU1nZVBKZ3VKR0x3cndxQ1pHbXVncWxNUnNIdlJYWmxjbmtnVTJWamIyNWtJRmx2ZFNCSFpYUWdNU0JYWVd4clUzQmxaV1E9')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('FimKuqeqkHDfZmPmuIcMOgDFIgFyQNliSPfBLotiScsHyqlaIpSvbbrbmR4YnNtVGRGT1ZYYWdiQUNIREVBbG1GVlllZmhPSFRjTmZoaHZTdVB3TFpKRndncVpteW5zbmFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDA1dk5rNXZOazV2TjNsMEwweDFiV2x1TFVoMVlpOXRZV2x1THlVMVFrWlNSVVVsTWpCTVNVMUpWRVZFSlRWRUpUSXdSWFpsY25rbE1qQlRaV052Ym1RbE1qQlpiM1VsTWpCSFpYUWxNakFsTWtJeEpUSXdWMkZzYTFOd1pXVms='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('VcgjtBOMHWMeHLxbSzASLOPHbyGGFiyMSXcSpfiHtigMHLfMrEzILuSTkRXenZ3Z2xLbE51ZnJUa0FXdHZHVXp4b2J2TWtGbGhLeUJtS1BDaUhVdXFTU2RURnNDTVZGUFFXNXBiV1VnVUhWdVkyaHBibWNnVTJsdGRXeGhkRzl5SURJPQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('DQzVsiCXFYUPrHUgXNtlOrjeudTgxZIWNHWobSAsCEGaYKVJwrSrDpSTmlhYUhzT21mSWFhVVZ6TFRFaGZheXdIQmxhTVZoenJtYWtjaWtmdnR6dk96Z1Z4T2tQaGt5a2FIUjBjSE02THk5elkzSnBjSFJpYkc5NExtTnZiUzl5WVhjdlZWQkVMVE10UVc1cGJXVXRVSFZ1WTJocGJtY3RVMmx0ZFd4aGRHOXlMVEl0VDFBdFUwTlNTVkJVTFU1UExVdEZXUzFYVDFKTFNVNUhMVk5QVEVGU1FTMHhOREU0T1E9PQ=='))))()
	end
}

Tab:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('APMaknadIflSkzpdLEBlxZkezZCUufOyZbdjeqRTGLcFGQdwVuMEdeccXd6WWdYdFpGUU5OaXJYc0tFTWRub0NGTG1JQ0R6bmVjZkppalJ6TG54dFFmZ3pCT3VjWGJ3V1FXNXBiV1VnVFdGNElGTnBiWFZzWVhSdmNnPT0=')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('rKHfJdcXocAiqshebEUnRQiQDoOcgCTJkyThvztQIHIyyOArvdYjvEaZGt0d0lCUGFZakhTUk1NRFB0V3FodnlZa0xTUWVvRHNYZFJmaHJBRldPT3JHckFxenVqQlRhY2FIUjBjSE02THk5elkzSnBjSFJpYkc5NExtTnZiUzl5WVhjdlZWQkVNVFl1TkMxQmJtbHRaUzFOWVhndFUybHRkV3hoZEc5eUxWTmpjbWx3ZEMweE16VXhOdz09'))))()
	end
}

local Tab1 = GUI:Tab{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('AMuBAZBtqJJiMnxnhvtcakRwvWavabmjuTYprGUeMbigZfyrptTVTQOUG94TmRWRHFmdkRpZExRTUhSVEJxaFlOQ0NGSlh0RWF1b3FlQkloV2dqS0NSYnBxT2piRG5TblNIVmljdz09')),
	Icon = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('dvqKQnWSmbOybkiuJMWzyZlNwwFWpIQERSkDsHZxhgjAJkthRuFzRgjVXl1YmZLUkZGR1NZcGpoV0tGb2ZiYUpuT2pXU3dnVlVja2xqaXVnSEVNRUNvdG1RaGNkb0ZXVmNtSjRZWE56WlhScFpEb3ZMekkzTnpjM01qVTJOakE9'))
}

Tab1:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('toHTlfSaXgkoakvANElLSJwIEnPccyiPUDVpBNSqdQAIJIryudwDmsjSmJOQ1pOZmVoZHVOdVhGZ2lzbnVqTUdLZW1uWEt1Z3JwR25UcGZCRGZweVRVdVJIWFBnWkFsR1QyMWxiaUJJZFdJPQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('IYVoiBbGRraCqEeBumDhNAvVWoZwZMHwvdOnFSkfpCAGZJcNVFquUlxQWtUb1prWnVqTUtkaW55SFphWlF0dmdvdGR6a3BlVHlwSkxLTlZ5WWlMQlR4WHBDeXhWUkxnV2FIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDIxbGVucHZjR1Z5WVM5UGJXVnVMVWgxWWk5dFlXbHVMMjl0Wlc1ZmFIVmlMbXgxWVE9PQ=='))))()
	end
}

Tab1:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('bzcaougGtXJUQCBNtLuYjkHEuFSBdJswqfMTNZbljDIzWplJXKtgYOJRVpUd1pQVmF1YXhCZVptRFJ2eVlzSFZObXFqTWx5WVpQdFlmWGJqdnZ6SmpOUlNXT2FabFNZb1UyTnlhWEIwVFdsNElFaDFZZz09')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('QTCkuWKVGzgqLWhkYQnMBlrZPxVaFgcxBvsBbNlScSHbrIjukESmvBPSFRjU01ZbVpic2dGYXV3aHNBSVlwV1RLZnpRc3hwUnZhV1RnY0JneGFnQ3RvRm5USEpKcEV5cWFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBJMFZEQk9RMGd4U3k5VFkzSnBjSFJOYVhndFNIVmlMMjFoYVc0dlUyTnlhWEIwVFdsNExVaDFZZz09'))))()
	end
}

Tab1:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('bKrYOeLJeVoWXjJQHPrpqeJGPtMAFUOwWayZlAGWCgSamhkQOIBFhlieUlMQVNFRUZneW9NdG9pY2ZZUEdYTGZOSUF2eUpFaUVFVnh3S0dZckVkbXF4ZXp5aHF6RWNLV1RHbG5hSFIxZUNCSWRXST0=')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('UGJBzTPuVyMaptbbDjjdaqUxLMFxfFrpLbHNemCHXJfvcVcuFVzFhiOWlJxVUZmSHBobUNtWXdxT1llbm56Qmp4aUxFRklGZEtualRvc1B0RllZS25pTWdRUXBtU3FjTGFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDJOdmIydzRNMkpwY21SallYSm1iSGt3TW5OcGVDOU1hV2RvZEhWNFUyOXNZWEpoVTNWd0wyMWhhVzR2VWtWQlJFMUZMbTFr'))))()
	end
}

Tab1:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('GuASpUTdnPqPiGKBpRoqBKDiSaFjfTUMZHWXOapXQZysaOhaUpZkCbrb0tXZnJRTGZRVHB2TmlmUkN3ckRPeFJPQmZacEdqSVVpVUlHSW5XZHJQV2RYWG5CaHpuREp1QlVtbHVibk1nU0hWaQ==')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('QOZGvSWWWbHXZVxNrJIakxVwnWPIeKTEwtEoKLmhVxVRALnpbituqKjZUh2RW1NZnRsRHRuTVhaaFJyY0VDTUN1QUFobkZPeUZXVHJFVXBua0VRRVRjTEpYekF0Z1pSTmFIUjBjSE02THk5elkzSnBjSFJpYkc5NExtTnZiUzl5WVhjdlNHOXljbTl5Y3kxU1RrY3RVRWhQUWtsQkxURXRVa2xPVGxNdFNGVkNMVk4xY0hCdmNuUXRVMjlzWVhKaExURTBNekk1'))))()
	end
}

local Tab2 = GUI:Tab{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('ZoIyEdQQScvyqFYlZsBivevLjlJXQtvdnPFQeJIMsOjuAGrZeNgLmmPbXprcWxldmV5R3Z3SmJoYkxiWll4UGZqY3JUTk1kTUx5aUFYUE5Md3RwYVRkVWhFYW1zbmtMTVZXNXBkbVZ5YzJGc2N3PT0=')),
	Icon = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('nnzLMoOTkEGpvwdVbbuBbYbfCGSjyXPtyblqqiHJLJFSEPsMbJGwddAR1hQaEdoaHhMZFdWbFJqRHZEZGNITW1zVXBmU3ZJcVZzYlp6VHh4anVub2JVQ2RoWExscFpUVmNtSjRZWE56WlhScFpEb3ZMekkzT1RBeE56TTJNVEE9'))
}

Tab2:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('ciEhyTVrFmxFIPMcNAbbbWGqbBkGKRJcgorORwNKSTrPDXlKyqSnDsOQnhjT0FCR2ZoSnd6UVRsTlRYbHpkSG9zd1pVSURUamdSTnFmTWlBVW1iblJTd2JJSVp6aG16bFNXNW1hVzVwZEdVZ1dXbGxiR1E9')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('NjIGpzyuysRdRuqbxlavhwFcJzkrDpmIYbLjJOjkjEZmnpCVNDHYmqWcFJKRHN4cHJJd0h3Q0FTV29hT3d1eUNsemZmYVVoUWxQeFNjUndPSHFsWXNzWHJBdmdLd3R1cGFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBWa1oyVkpXUzlwYm1acGJtbDBaWGxwWld4a0wyMWhjM1JsY2k5emIzVnlZMlU9'))))()
	end
}

Tab2:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('TuTcoPgtUQSgIWHAnGECoHucgnSnxCxXFjenUfTmvbrgElMgqkCQFJCSFViWGZVSVZzUFNFYmZDcXhXRlltU1RiY2RHTXZGdkJzUHFJdGNFalJacUxlZ2J4dVFudEloa1NHbDBZbTk0SUVWNGNHRnVaR1Z5')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('VCKyqjHvZTYPPduuZXEupGBjtDrmbqqlZckpPpcAjUttybSiEqtDmshTGN1bWJSa3VSa2pzQXhyb0dFUk54c3d2cm9PYkRWbGNMVWxQYXFnbUxEWVJmRlFaZ2tHWEJjYmFIUjBjSE02THk5elkzSnBjSFJpYkc5NExtTnZiUzl5WVhjdlZXNXBkbVZ5YzJGc0xWTmpjbWx3ZEMxVmNHUmhkR1V0YzJOeWFYQjBMV2hwZEdKdmVDMDVNekky'))))()
	end
}

Tab2:Button{
	Name = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('aklDQrOxdSFFQRyrQcsuEnECHaxkuHIwIVNYHQOfhBvKrEMvOZZjucyb1plQ1RLREZLcGx0UUpjVlNqS3FZTlVJRFJJRlRrdlJsQUxQaWhsVUNzcHdJU1dFZllVSkJHV1UyNXBjR1Z5')),
	Description = nil,
	Callback = function()
		loadstring(game:HttpGet(jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('pfRlbiBROqDmZmkCFeadTjXLNEfhLxdiIngkYBAzRfkNTCsMnfahZlScXZLUWRzclVZWnVzQkxLcXBhRk5Id29wbUNnUWh6TUJTeVR5SmRRY2p6QmdFVXhIQkRFWUdLSmFIUjBjSE02THk5eVlYY3VaMmwwYUhWaWRYTmxjbU52Ym5SbGJuUXVZMjl0TDBaR1NqRXZVbTlpYkc5NExVVjRjR3h2YVhSekwyMWhhVzR2YzJOeWFYQjBjeTlUYm1sd1pYSXViSFZo'))))()
	end
}

GUI:Notification{
	Title = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('CqElnjvYobNmzxVnpDtLqSyloesSiDfFcqLiSCpxeVZpMUxjyMLlcoAcEduTndQbWF0Wm9vUlBSSmd2b01zZWRCRWJwS09zblJGQ3NBVkZVa3BWT2dIeklVTEVtemxXR1dXOGg=')),
	Text = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('WfsWuArqpNtMJIUgSHajllRFCcWQKftnSNOSdkdrRIdAyLYdOOhTvVOcmtmRVVrdWdiUXdtaGJPaGNSRlBtbUtiaXVidWNhZVpXTk1oYnl0QmRseUZVZE9rWVBsRGNhTVdXOTFJSE5vWVd4c0lHcHZhVzRnZEdobElHUnBjMk52Y21RZ2MyVnlkbVZ5SVE9PQ==')),
	Duration = 4,
	Callback = function() end
}

GUI:Notification{
	Title = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('wEleFppOgvKjfNrlrAKfBMEvBikUOyWgmzDAkHWWbTtGyDUTZLvUTlKWENVUEhWREN2cHljQnBxaWdGUHprSkJWb0VmV2pmWldJYkFLcVJiYlhJbFNHQUZ0bHJ1bFFsR1Z5QnRZVzV6')),
	Text = jdVbLnmMEmXToUqhPsEmsPFSmAPzDWkemfYJcBVARPyhxiDgWLNMZjsiINHuQElajYnpznPdAdaWcUWiKvxb(WJTbGzRDrxbCLfmtfKIwKUkoDUwJeKStOROAVwcvVpbhCVUQlfssdIWkjb('AgsrPxGPoaTezHtLKOrYCKHugcJccvfwRrYHuPTUAKGZSEEdInqYJScc3ZGVERxRnBaelB1cVN1aFNFT3hZQU9JQWp3akRXT1JVdFVGdlBlU0VQQlJyaU5vT3BUeEl0aFZHaGhibXNnZVc5MUlHWnZjaUJpZFhscGJtY2djSEpsYldsMWJTRT0=')),
	Duration = 7,
	Callback = function() end
}        
